name: Copilot Setup Steps

on:
  workflow_dispatch:
  # This workflow is automatically triggered before Copilot starts working

jobs:
  copilot-setup-steps:
    name: Setup Copilot Environment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install system dependencies for PyQt6
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libgl1 libxkbcommon-x11-0 xvfb
        sudo apt-get install -y libxcb-xinerama0 libxcb-cursor0 libxcb-shape0
        
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install development dependencies
      run: |
        pip install -e ".[dev]"
        
    - name: Install PyQt6 specific linting tools
      run: |
        pip install pyqt6-stubs
        
    - name: Verify installation
      run: |
        python --version
        pip list | grep -E "(PyQt6|pylint|pytest)"
        
    - name: Test basic functionality
      run: |
        # Run a quick smoke test to ensure environment is working
        DISPLAY=:99 xvfb-run -a python -c "
        import sys
        print('Python version:', sys.version)
        
        # Test PyQt6 import
        try:
            from PyQt6.QtWidgets import QApplication
            print('✅ PyQt6 import successful')
        except ImportError as e:
            print('❌ PyQt6 import failed:', e)
            sys.exit(1)
            
        # Test pylint availability
        try:
            import pylint
            print('✅ Pylint available')
        except ImportError as e:
            print('❌ Pylint not available:', e)
            sys.exit(1)
            
        # Test pytest availability  
        try:
            import pytest
            print('✅ Pytest available')
        except ImportError as e:
            print('❌ Pytest not available:', e)
            sys.exit(1)
            
        print('🎉 Environment setup successful!')
        "
        
    - name: Run quick validation
      run: |
        # Run a subset of tests to validate the environment
        DISPLAY=:99 xvfb-run -a python -m pytest tests/test_logic/ -v --tb=short
        
    - name: Validate linting setup
      run: |
        # Test pylint configuration
        python -m pylint --version
        python -m pylint py_fade/app.py --score=yes
        
    - name: Environment summary
      run: |
        echo "🚀 Copilot environment ready!"
        echo "✅ Python 3.11 installed"
        echo "✅ PyQt6 with system dependencies"
        echo "✅ All development tools (pylint, pytest, yapf)"  
        echo "✅ PyQt6-specific linting tools"
        echo "✅ X11/Xvfb display for GUI testing"
        echo ""
        echo "Available commands:"
        echo "  - pytest: Run test suite"
        echo "  - pylint: Run code analysis" 
        echo "  - yapf: Format code"
        echo "  - ci-qa: Run unified CI checks (pytest + pylint)"